### ISSUE TITLE
Week 05 - Day 2 - JavaScript Iteration

### ISSUE THREAD

**Issue by gstark** [StPeteFrank/assignments#16]
# JavaScript Iteration

## Objectives

After completing this assignment, you should be able to:

* Demonstrate an understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/js-iteration) to your own account.
2. Change into your projects directory:
3. Clone your repository: `git clone js-iteration`
4. Change into your project's directory: `cd js-iteration`
5. Install the dependencies: `yarn install` (or just `yarn` for short)
6. Open in your editor]
7. Start the test runner: `yarn test`
7. Open `src/functions.test.js` and work on functions until tests pass.
8. Commit and push your work to GitHub.
9. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing
- No linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Additional Resources

Reference the documentation on DevDocs to find what kind of helpful functions might already be in JavaScript.

- [String Functions on DevDocs](https://devdocs.io/javascript/global_objects/string).
- [Array Functions on DevDocs](http://devdocs.io/javascript/global_objects/array).

**Comment by StPeteFrank** [comment]
Hey Gavin. Here is my github repo url for js-Iteration assignment. This will become my start of day coding assignment until I get to Code Wars Katas level. Thank you for your help. Once I understand the last three I'll resubmit and comment.

https://github.com/StPeteFrank/js-iteration

**Comment by gstark** [comment]
Awesome!

For things like

```
    number = number % 2 === 0
    return number
```

just do  `return (number % 2 ==== 0)`

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e11f1f3541d668540d195fe7adcb68fd773344b8/giphy-12.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/77)**__
