### ISSUE TITLE
Week 06 - Day 2 - One List

### ISSUE THREAD

**Issue by gstark** [StPeteFrank/assignments#19]
In this assignment, you'll build a classic todo manager.

Something like: [One List](https://one-list.ambetha.surge.sh)

## Objectives

- Reinforce component architecture in React
- Effective use props and state in React

## Requirements

We're going to build todo manager. The user should be able to:
- Add new todo items
- Mark todo items as complete
- Delete todo items

Read the [documentation](https://one-list-api.herokuapp.com)

### Explorer Mode

- [x] Allow a todo to be created
- [x] Mark a todo complete
- [x] Delete a todo item

### Adventure Mode

- [ ] Allow the text of a todo item to be changed

### Epic Mode

- [ ] Allow for multiple lists by allowing the user to specify the `access token`

**Comment by StPeteFrank** [comment]
Explorer mode good to go. Postman is dope.

https://github.com/StPeteFrank/one-list

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
