### ISSUE TITLE
Week 01 - Day 2 - Expanding Your World

### ISSUE THREAD

**Issue by gstark** [StPeteFrank/assignments#2]
In this assignment you will end up with a simple styled web page, published on the web.

## Objectives

- Practice using your tools text editor
- Explore new CSS properties
- Publish a web page

## Requirements

- Have `git`, `hub`, and `node` installed. We should have done this together in class.

### Explorer Mode

- [x] Follow all of the setup instructions (See "Assignment Setup").
- [x] Using CSS, style your page to imitate some of the classic designs of the web. Feel free to make this look as "bad" as you want. Here are some sites to gain inspiration:
  - [10 90s websites designs you won’t believe existed](https://www.justinmind.com/blog/10-90s-websites-designs-you-wont-believe-existed/)
- [x] Add a second page about your hobby with (at least) 2 pictures and with other facts about your hobby.
- [x] Add a menu to the your site so a user can go back and forth between the new pages.
- [x] Between the 2 pages, use at least 5 tag selectors, 5 id selectors, and 5 class selectors to style content on your page.
- [x] Deploy your site.

### Adventure Mode

- [ ] use pseudo-classes to style elements when you hover the mouse over them
- [ ] Add a third page, that has a table. Create this table to have alternating colored rows, and a hover over color.
- [ ] Make a nav bar that sticks to the top of the page (see the nav bar here for example: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)
- [ ] Make a footer that always sticks to the bottom of the page

### Epic Mode

- [ ] Explore CSS animations and add some life to your static page. Feel free to really dig into these and try to animated all elements on your page to some extent

### CSS

- [Introduction to CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS)
- [Getting Started with CSS Rules](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#Anatomy_of_a_CSS_ruleset)
- [All the CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index)
- [pseudo-classes and pseudo-elements](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Pseudo-classes_and_pseudo-elements)

### HTML

- [HTML Tags](https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags)
- [Evolution of the Web](http://www.evolutionoftheweb.com)

## Reading Material

To prep for tomorrow's lesson, you can [read about flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

**Comment by StPeteFrank** [comment]
Hi Gavin. Here is my URL for the Expand Your World HW. Looking forward to following up on margins, borders, padding, and flex. I was just getting used to the GitHub processes today and feel that it slowed me down on those items. See you tomorrow. Thank you!

http://expanding-frankdiaz.surge.sh

and

expanding-frankdiaz.surge.sh

**Comment by gstark** [comment]
Hi Frank, you gave the `surge` link twice. I need the `github.com` link. This is the URL for this repository if you visit your personal page on `github.com` and find the `expanding` repository.

**Comment by StPeteFrank** [comment]
https://github.com/StPeteFrank/expanding/commit/f4af6452708515cc9ed5cee382c8ae5cca65d84b

Gavin, is this he right URL?

Thx

**Comment by gstark** [comment]
No, the link should just be the URL at the top of the page when looking at the main page of your repository.

The link above is fine, for now.

![screencast 2018-10-25 08-30-04](https://user-images.githubusercontent.com/2607/47500262-5459c800-d830-11e8-8b7b-c2eba99a0fa8.gif)

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
