### ISSUE TITLE
Week 06 - Day 3 - Choose your own API

### ISSUE THREAD

**Issue by gstark** [StPeteFrank/assignments#20]
In this assignment, you'll build a front end for an API of your choice

![Snowman](./assets/snowman.gif)

## Objectives

- Reinforce component architecture in React
- Reinforce reading of API documentation (some is great, and some is terrible)
- Creating and designing your own features for a web app

## Requirements

We're going to build a front end for an API of your choice. Choose one from [this list](https://github.com/toddmotto/public-apis)

*NOTE* You'll need to choose one with `Auth` being `No` or `apiKey` since we haven't covered `OAuth` authentication yet.

*NOTE* You'll also need to check to see if the API will work from your browser. You can do a quick check by making a small `create-react-app`, doing an `axios.get` or `fetch` of one API URL and see if you get browser errors.

### Explorer Mode

- [x] Read your API docs
- [x] Use Postman to make some API requests to be familiar with the API and the data it returns
- [x] Create a list of the features you are going to create and how they will work
- [x] Design your User Interface
- [x] create-react-app
- [x] Design your HTML statically in `App.js`
- [x] Make it dynamic
- [x] Use components when needed
- [x] Deploy it and share it with friends

**Comment by StPeteFrank** [comment]
Choose your own API created with react router library.

https://github.com/StPeteFrank/picture-a-dog

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03a26be8c53c7287bc40570f4006121a970942ce/giphy-5.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/70)**__
