### ISSUE TITLE
Week 08 - Day 1 - A Whole New World

### ISSUE THREAD

**Issue by gstark** [StPeteFrank/assignments#24]
---
title: A Whole New World
draft: true
---

Today you learned a new language and will be starting to explore it more in depth in the coming weeks. Like any good craftsman, the first thing you need is to learn your tools. Tonight, you will be setting up your developer environment, creating a simple console application, and writing a short blog. 

## Objectives

* Set up your dev machines
* Create a simple console application to ensure your machine is set up correctly
* Write a blog article to practice talking about technology 

### .NET Students 

 - Install the .NET Core SDK here: [https://www.microsoft.com/net/download](https://www.microsoft.com/net/download)
- Install the `C#` plugin in VS Code. 

- To verify everything was installed correctly, run `dotnet -v` in your terminal.

### Ruby

You should already have Ruby installed. 

#### Simple Console Application 
* [x] Create a console application that guesses a number that a user has thought of , between 1 and 100. This will use a [binary search`](https://www.programmerinterview.com/index.php/puzzles/minimum-guesses-1-100/) to guess the correct number 

* [x] Here is the JavaScript, in the browser, algorithm to follow. Make sure to understand this first before writing new code: [`https://codepen.io/ambethia/pen/KNewBb`](https://codepen.io/ambethia/pen/KNewBb). 
**NOTE** You will be translating this from the event-driven paradigm of HTML to the more procedural paradigm of a console application. 
* [x] For Explorer Mode, you do not have to put in a menu or other user experience "nice to have" features, focus on the just the core algorithm.

### Adventure Mode

* [ ] Create a nice user experience. Include features such as 
`Try again` and `Welcome, press enter to start`

### Epic Mode

* [ ] Eventually we will be using an MVC application structure. To prepare for this, refactor your code to have all your business logic in a separate class and all your console interaction in the main class. 

## Additional Resources

* Ruby Resouces: 
    - [While loops](https://learnrubythehardway.org/book/ex33.html)

* .NET
    - [https://docs.microsoft.com/en-us/dotnet/](https://docs.microsoft.com/en-us/dotnet/)

## Reading Material

**Ruby**: Read and work through exercise 14 of [Learn Ruby the Hard Way](https://learnrubythehardway.org/book)

**Comment by StPeteFrank** [comment]
Okay, not publishing this one but here's the link to my react non-technical explanation article.

https://medium.com/@diazfrankp/what-does-react-js-do-24a94097345

Here's my number picker C# practice app.

https://github.com/StPeteFrank/numberpicker

**Comment by mdewey** [comment]
2 really small pieces of feedback

- In your blog, you said "...is basically...", a general tip, "basically" is verbal filler, if you drop that from your vocabulary when talking about tech it will sound better. 

- In your git repo for the code snippet. do not forget to add a gitingore, we can look at how to do this easily together

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3c87e39487e11776789d2fa19615334abd2e3aab/giphy-1.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/66)**__
