### ISSUE TITLE
Week 02 - Day 2 - Roshambo

### ISSUE THREAD

**Issue by gstark** [StPeteFrank/assignments#6]
Create a simple Rock-Paper-Scissors game.

## Objectives

- Work with JavaScript and the DOM
- Practice conditional logic

## Requirements

Do not worry about CSS for explorer mode, only do as HTML to show the functionality.

### Background

See the wikipedia page about [Rock, Paper, Scissors](https://en.wikipedia.org/wiki/Rock%E2%80%93paper%E2%80%93scissors)

### How to get started

- Get familiar with rock, paper, scissors if you haven't played before (or in a while)
- Draw out on paper/whiteboard/computer the rough design of your application
  - See _Explorer Mode_ for the UI requirements
- Start by placing all the HTML elements on the page
- Style the user interface
- Write out in English, ALL the steps the application needs to take
  - For example "When user one clicks on Rock, remember that user one chooses Rock"
- Start adding JavaScript to make your program to do the steps you described above

### Explorer Mode

- [x] As a user I should be able to see three buttons for each player.
- [x] As a user, I should be able to pick an option for each player.
- [x] As a user, after each player makes their selection, I should be told who won and the game should be over.

### Adventure Mode

- [ ] Create a `vs computer` mode, that picks a selection.
- [ ] Modify your `vs computer` mode to follow a specific strategy (your choice)
- [ ] Make your computer AI unbeatable
- [ ] Give the user a choice to player against the various computer levels or another player
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable

### Epic Mode

- [ ] Your game is currently only 1 vs 1, add the ability to add more computer or users players to the game

**Comment by StPeteFrank** [comment]
Hey Gavin. Here is my Roshambo homework. Im just wrapping my head around Javascript. I understand the processes and theories but still struggle actually putting it down on the screen. I get the variables, values, assigning functions, and declaring functions. Im still in the haze a bit on actually writing it. Ready for more practice and lessons please!

https://github.com/StPeteFrank/roshambo/tree/master/public

**Comment by gstark** [comment]
Frank, this is great! My *ONLY* comments are:

1) Don't leave commented out code such as `// document.querySelector('h1').textContent += '?'` behind

2) `player1choice` would be a better variable name than `p1choice`

_very_ nicely done!

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__
